import { KeyValue } from "@/interfaces";

const TabErrors: KeyValue<string>[] = [
    {key: 'brand', value: 'auction'},
    {key: 'model', value: 'auction'},
    {key: 'year', value: 'auction'},
    {key: 'vin', value: 'auction'},
    {key: 'purchased_at', value: 'auction'},
    {key: 'price_for_car', value: 'payment'},
    {key: 'transfer_data.title', value: 'payment'},
    {key: 'transfer_data.bank.name', value: 'payment'},
    {key: 'transfer_data.bank.city', value: 'payment'},
    {key: 'transfer_data.bank.country', value: 'payment'},
    {key: 'transfer_data.bank.swift', value: 'payment'},
    {key: 'transfer_data.bank.number', value: 'payment'},
    {key: 'transfer_data.recipient_name', value: 'payment'},
    {key: 'transfer_data.account_number', value: 'payment'},
    {key: 'transfer_data.amount', value: 'payment'},
    {key: 'transfer_data.currency', value: 'payment'},
    {key: 'price_for_additional_payment', value: 'payment'},
    {key: 'additional_payment_transfer_data.title', value: 'payment'},
    {key: 'additional_payment_transfer_data.bank.name', value: 'payment'},
    {key: 'additional_payment_transfer_data.bank.city', value: 'payment'},
    {key: 'additional_payment_transfer_data.bank.country', value: 'payment'},
    {key: 'additional_payment_transfer_data.bank.swift', value: 'payment'},
    {key: 'additional_payment_transfer_data.bank.number', value: 'payment'},
    {key: 'additional_payment_transfer_data.recipient_name', value: 'payment'},
    {key: 'additional_payment_transfer_data.account_number', value: 'payment'},
    {key: 'additional_payment_transfer_data.amount', value: 'payment'},
    {key: 'additional_payment_transfer_data.currency', value: 'payment'},
    {key: 'tracking_link', value: 'tracking'},
    {key: 'contractor_number', value: 'tracking'},
    {key: 'eta', value: 'tracking'},
    {key: 'price_for_excise', value: 'excise'},
    {key: 'excise_transfer_data.title', value: 'excise'},
    {key: 'excise_transfer_data.bank.name', value: 'excise'},
    {key: 'excise_transfer_data.bank.city', value: 'excise'},
    {key: 'excise_transfer_data.bank.country', value: 'excise'},
    {key: 'excise_transfer_data.bank.swift', value: 'excise'},
    {key: 'excise_transfer_data.bank.number', value: 'excise'},
    {key: 'excise_transfer_data.recipient_name', value: 'excise'},
    {key: 'excise_transfer_data.account_number', value: 'excise'},
    {key: 'excise_transfer_data.amount', value: 'excise'},
    {key: 'excise_transfer_data.currency', value: 'excise'},
];

export { TabErrors };
